apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KCSJhdXRocyI6IHsNCgkJImdoY3IuaW8vKiI6IHsNCgkJCSJhdXRoIjogImIyeG5ZV3h2ZEd0aE9tZG9jRjlJZFRWb1FXdFFiR0Y1VGxwdlVVUkxWMGsyZHpKSFNGSmFUSGsxV0hVemFrNVdibTQiDQoJCX0NCgl9DQp9

type: kubernetes.io/dockerconfigjson
